Enables local development without throwing argument errors.
Recent changes prevented local execution of the tool, returning an error
of "TypeError: cli() missing 1 required positional argument: 'cli_args'"